services:
  challenger-api:
    build:
      context: .
      platforms:
        - linux/amd64
    restart: unless-stopped
    platform: linux/amd64
    privileged: true
    ulimits:
      nofile: 32768
    environment:
      TERM: ${TERM:-xterm}
      TZ: UTC
      ZFBI_API_PORT: ${ZFBI_API_PORT:-10001}
      ZFBI_CHALLENGE_API_KEY: ${ZFBI_CHALLENGE_API_KEY:-challenge_api_key}
      ZFBI_CHALLENGE_VERIFICATION_API_KEY: ${ZFBI_CHALLENGE_VERIFICATION_API_KEY:-super_secure_api_key}
      ZFBI_CHALLENGE_VERIFICATION_ENDPOINT: ${ZFBI_CHALLENGE_VERIFICATION_ENDPOINT:-http://challenge_server:8000/api/v1/verify}
      ZFBI_CHALLENGE_VERIFICATION_STARTUP_URL: ${ZFBI_CHALLENGE_VERIFICATION_STARTUP_URL:-http://challenge_server:8000/start}
      NSTBROWSER_API_KEY: ${NSTBROWSER_API_KEY:-nstbrowser_api_key}
      NSTBROWSER_PROFILE_ID: ${NSTBROWSER_PROFILE_ID:-profile_id}
      NSTBROWSER_HOST: ${NSTBROWSER_HOST:-api.nstbrowser.com}
      NSTBROWSER_PORT: ${NSTBROWSER_PORT:-443}
      NSTBROWSER_PROTOCOL: ${NSTBROWSER_PROTOCOL:-https}
    env_file:
      - path: .env
        required: false
    volumes:
      - "api-logs:${ZFBI_API_LOGS_DIR:-/var/log/rest.rt-zfbi-challenger}"
      - "api-data:${ZFBI_API_DATA_DIR:-/var/lib/rest.rt-fbi-challenger}"
    ports:
      - "${ZFBI_API_PORT:-10001}:${ZFBI_API_PORT:-10001}"
    tty: true

volumes:
  api-logs:
  api-data:
