challenge:
  api_key: "challenge_api_key"
  docker_ulimit: 32768
  bot_timeout: 10
  repeated_framework_count: 3
  human_injection_count: 10
  verification:
    endpoint: "http://challenge_server:8000/api/v1/verify"
    api_key: "super_secure_api_key"
    startup_url: "http://challenge_server:8000/start"
    extra: {}
  framework_images:
    - name: seleniumbase
      image: redteamsubnet61/seleniumbase@sha256:6528bddec31a31e4b8cd2a3940cf34d7697abb4356e02c44ad362eb899c751ed
