challenge:
  api_key: "challenge_api_key"
  docker_ulimit: 32768
  bot_timeout: 10
  repeated_framework_count: 3
  human_injection_count: 10
  allowed_automation_miss_count: 2
  nstbrowser:
    api_key: "nstbrowser_api_key"
    host: "localhost"
    port: 8848
    protocol: "http"
  verification:
    endpoint: "http://challenge_server:8000/api/v1/verify"
    api_key: "super_secure_api_key"
    startup_url: "http://challenge_server:8000/start"
    extra: {}
  framework_images:
    - name: nodriver
      image: abdibekbolot/anti-detect-browsers:nodriver@sha256:440916fe1800caf483a9105d484e2570672e74a5910afc5955c6aff7528a5d44
    - name: playwright
      image: abdibekbolot/anti-detect-browsers:playright@sha256:96bf78cf38824d58099a44183625bc5923c4d3a2d2baa42a77fe8da0cb654a31
    - name: patchright
      image: abdibekbolot/anti-detect-browsers:patchright@sha256:34a5593c21c4a246476def8c0fefb2123c067de5c93189b9c4889dfe7b7d0e1d
    - name: puppeteer
      image: abdibekbolot/anti-detect-browsers:puppeteer@sha256:7460857027ef130f4bfee528a0cfb891d4c6a0f7bfc6480749562ad7070dd1b6